### ISSUE TITLE
java.lang.NoSuchMethodException: linc.com.amplituda.Amplituda.fromPath

### ISSUE THREAD

**Issue by anasmadrhar** [massoudss/waveformSeekBar#27]
I'm getting this while trying to use getSampleFrom(path). I'm using 
    implementation  'com.github.massoudss:waveformSeekBar:3.0.0'
    implementation 'com.github.lincollincol:Amplituda:2.0.3'

> 2021-08-01 18:05:37.151 11229-11229/chitter.anonymous.chat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chitter.anonymous.chat, PID: 11229
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139) 
     Caused by: java.lang.NoSuchMethodException: linc.com.amplituda.Amplituda.fromPath [class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.masoudss.lib.utils.ExternalAmplituda.run(ExternalAmplituda.kt:50)
        at com.masoudss.lib.utils.WaveformOptions.getSampleFrom(WaveformOptions.kt:18)
        at com.masoudss.lib.WaveformSeekBar.setSampleFrom(WaveformSeekBar.kt:254)
        at com.masoudss.lib.WaveformSeekBar.setSampleFrom(WaveformSeekBar.kt:248)
        at chitter.anonymous.chat.components.chat_voice_player.VoicePlayerView.setAudio(VoicePlayerView.kt:107)
        at chitter.anonymous.chat.ui.new_chat.chat.FriendMessageListAdapter$SentAudioMessageHolder.bind(FriendMessageListAdapter.kt:582)
        at chitter.anonymous.chat.ui.new_chat.chat.FriendMessageListAdapter.onBindViewHolder(FriendMessageListAdapter.kt:171)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1867)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5260)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:740)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)

**Comment by lincollincol** [comment]
@anasmadrhar Hi, please use Amplituda version 1.7 => `implementation 'com.github.lincollincol:Amplituda:1.7'`
This bug will be fixed soon in the new Amplituda version. I'll let you know here
