### ISSUE TITLE
Fatal Exception: SetSample

### ISSUE THREAD

**Issue by xeinebiu** [massoudss/waveformSeekBar#3]
Hi.
I am getting an fatal error:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xeinebiu.anplayer, PID: 24232
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: com.masoudss.lib.exception.SampleDataException: Set the sample data by using WaveformSeekBar.setSample method.
        at com.masoudss.lib.WaveformSeekBar.onDraw(WaveformSeekBar.kt:73)
        at android.view.View.draw(View.java:21859)
        at android.view.View.updateDisplayListIfDirty(View.java:20732)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.updateDisplayListIfDirty(View.java:20718)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.draw(View.java:21862)
        at android.view.View.updateDisplayListIfDirty(View.java:20732)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.updateDisplayListIfDirty(View.java:20718)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.updateDisplayListIfDirty(View.java:20718)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.draw(View.java:21862)
        at android.view.View.updateDisplayListIfDirty(View.java:20732)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.draw(View.java:21862)
        at android.view.View.updateDisplayListIfDirty(View.java:20732)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.updateDisplayListIfDirty(View.java:20718)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.updateDisplayListIfDirty(View.java:20718)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.updateDisplayListIfDirty(View.java:20718)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.updateDisplayListIfDirty(View.java:20718)
        at android.view.View.draw(View.java:21585)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4546)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4321)
        at android.view.View.draw(View.java:21862)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1083)
        at android.view.View.updateDisplayListIfDirty(View.java:20732)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3909)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3683)
E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2991)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1850)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        	... 3 more

This is how I use on XML:
        <com.masoudss.lib.WaveformSeekBar
            app:wave_progress="33"
            app:wave_width="5dp"
            app:wave_gap="2dp"
            app:wave_min_height="5dp"
            app:wave_corner_radius="2dp"
            app:wave_background_color="@android:color/holo_blue_dark"
            app:wave_progress_color="@android:color/holo_orange_light"
            app:wave_gravity="center"
            android:id="@+id/waveformSeekBar"
            android:layout_width="match_parent"
            android:layout_height="50dp"/>

**Comment by massoudss** [comment]
You should add samples to your view by calling `setSample` method.
If you don't, this view can not be drawn!

**Comment by xeinebiu** [comment]
Yes.

I call setSample and pass true to ignore the Extension.

File is AAC media type

**Comment by PBasil2020** [comment]
I am also facing a fatal issue due to sample not set. 

I gave an mp3 file, stored in R.raw. as sample still getting this error. Request you to share a sample application usage of the same.
