### ISSUE TITLE
IllegalArgumentException: WaveformSeekBar.onSizeChanged from Google Play Crash Logs

### ISSUE THREAD

**Issue by thelou1s** [massoudss/waveformSeekBar#33]
Crash Stacktrace

Samsung Galaxy A01

Android 11 (SDK 30)

2 Days Ago

java.lang.IllegalArgumentException

java.lang.IllegalArgumentException: 
  at android.graphics.Bitmap.createBitmap (Bitmap.java:1150)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:1117)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:1067)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:1028)
  at com.masoudss.lib.WaveformSeekBar.onSizeChanged (WaveformSeekBar.kt:72)
  at android.view.View.sizeChange (View.java:24682)
  at android.view.View.setFrame (View.java:24615)
  at android.view.View.layout (View.java:24472)
  at android.widget.RelativeLayout.onLayout (RelativeLayout.java:1103)
  at android.view.View.layout (View.java:24475)
  at android.view.ViewGroup.layout (ViewGroup.java:7383)
  at android.widget.RelativeLayout.onLayout (RelativeLayout.java:1103)
  at android.view.View.layout (View.java:24475)
  at android.view.ViewGroup.layout (ViewGroup.java:7383)
  at android.widget.RelativeLayout.onLayout (RelativeLayout.java:1103)
  at android.view.View.layout (View.java:24475)
  at android.view.ViewGroup.layout (ViewGroup.java:7383)
  at android.widget.RelativeLayout.onLayout (RelativeLayout.java:1103)
  at android.view.View.layout (View.java:24475)
  at android.view.ViewGroup.layout (ViewGroup.java:7383)
  at android.widget.RelativeLayout.onLayout (RelativeLayout.java:1103)
  at android.view.View.layout (View.java:24475)
  at android.view.ViewGroup.layout (ViewGroup.java:7383)
  at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins (RecyclerView.java:9587)
  at androidx.recyclerview.widget.GridLayoutManager.layoutChunk (GridLayoutManager.java:690)
  at androidx.recyclerview.widget.LinearLayoutManager.fill (LinearLayoutManager.java:1587)
  at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren (LinearLayoutManager.java:665)
  at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren (GridLayoutManager.java:170)
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:4134)
  at androidx.recyclerview.widget.RecyclerView.onMeasure (RecyclerView.java:3540)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1552)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:842)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:721)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1552)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:842)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:721)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1552)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:842)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:721)
  at android.view.View.measure (View.java:27131)
  at androidx.core.widget.NestedScrollView.measureChildWithMargins (NestedScrollView.java:1599)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at androidx.core.widget.NestedScrollView.onMeasure (NestedScrollView.java:585)
  at android.view.View.measure (View.java:27131)
  at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren (ConstraintLayout.java:1227)
  at androidx.constraintlayout.widget.ConstraintLayout.onMeasure (ConstraintLayout.java:1572)
  at android.view.View.measure (View.java:27131)
  at androidx.viewpager.widget.ViewPager.onMeasure (ViewPager.java:1638)
  at android.view.View.measure (View.java:27131)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:27131)
  at androidx.viewpager.widget.ViewPager.onMeasure (ViewPager.java:1638)
  at android.view.View.measure (View.java:27131)
  at android.widget.RelativeLayout.measureChildHorizontal (RelativeLayout.java:735)
  at android.widget.RelativeLayout.onMeasure (RelativeLayout.java:481)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1552)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:842)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:721)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:7951)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
  at com.android.internal.policy.DecorView.onMeasure (DecorView.java:1173)
  at android.view.View.measure (View.java:27131)
  at android.view.ViewRootImpl.performMeasure (ViewRootImpl.java:4187)
  at android.view.ViewRootImpl.measureHierarchy (ViewRootImpl.java:2936)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3204)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2618)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:9971)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1010)
  at android.view.Choreographer.doCallbacks (Choreographer.java:809)
  at android.view.Choreographer.doFrame (Choreographer.java:744)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:995)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8512)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1139)

**Comment by thelou1s** [comment]
low rates, only 1 user report 10 times 2 days ago

**Comment by thelou1s** [comment]
It occurs in high rates recently, as firebase shows below:

![image](https://user-images.githubusercontent.com/5654770/144591794-cecbb76a-7c63-4da7-9248-42b8ea2235e0.png)

logs:
```
Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1138)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1105)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1055)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1016)
       at com.masoudss.lib.WaveformSeekBar.onSizeChanged(WaveformSeekBar.kt:4)
       at android.view.View.sizeChange(View.java:23507)
       at android.view.View.setFrame(View.java:23459)
       at android.view.View.layout(View.java:23308)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:23313)
       at android.view.ViewGroup.layout(ViewGroup.java:6539)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:23313)
       at android.view.ViewGroup.layout(ViewGroup.java:6539)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:23313)
       at android.view.ViewGroup.layout(ViewGroup.java:6539)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:23313)
       at android.view.ViewGroup.layout(ViewGroup.java:6539)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:23313)
       at android.view.ViewGroup.layout(ViewGroup.java:6539)
       at androidx.recyclerview.widget.RecyclerView$o.A0(RecyclerView.java:3)
       at androidx.recyclerview.widget.GridLayoutManager.u2(GridLayoutManager.java:63)
       at androidx.recyclerview.widget.LinearLayoutManager.U1(LinearLayoutManager.java:9)
       at androidx.recyclerview.widget.LinearLayoutManager.Y0(LinearLayoutManager.java:59)
       at androidx.recyclerview.widget.GridLayoutManager.Y0(GridLayoutManager.java:3)
       at androidx.recyclerview.widget.RecyclerView.E(RecyclerView.java:8)
       at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:12)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25969)
       at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:5)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:1)
       at android.view.View.measure(View.java:25969)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
       at android.view.View.measure(View.java:25969)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:834)
       at android.view.View.measure(View.java:25969)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3905)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2620)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2887)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2340)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9057)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1040)
       at android.view.Choreographer.doCallbacks(Choreographer.java:864)
       at android.view.Choreographer.doFrame(Choreographer.java:791)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by massoudss** [comment]
Did you try the latest version?

**Comment by massoudss** [comment]
The issue is fixed now. please update to v5.0.0.
