### ISSUE TITLE
Crash while recreating UI component

### ISSUE THREAD

**Issue by jaime-gomez** [massoudss/waveformSeekBar#48]
We are getting this crash, is not common and we don't have any reproduction steps. Although still happens every now and then.

```kotlin
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6943)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1090)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5258)
        at android.view.View.invalidateInternal(View.java:13890)
        at android.view.View.invalidate(View.java:13854)
        at android.view.View.invalidate(View.java:13838)
        at com.masoudss.lib.WaveformSeekBar.setSample(SourceFile:11)
        at com.masoudss.lib.WaveformSeekBar$a.invoke(SourceFile:3)
        at com.masoudss.lib.WaveformSeekBar.setSampleFrom(SourceFile:11)
        at f.a.c.b.n.c.invokeSuspend(SourceFile:6)
        at e.w.k.a.a.resumeWith(SourceFile:4)
        at z.a.o0.run(SourceFile:18)
        at z.a.o2.a.y(SourceFile:1)
        at z.a.o2.a$a.run(SourceFile:11)
```

**Comment by massoudss** [comment]
It's not library related bug but it seems you're trying to change view from background thread.
When you gonna update your views, be sure you're doing that in main thread.
